name: E2E Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  
            - name: Install & Patch packages
              run: yarn install
            
            - name: Build
              run: yarn build

            - name: Run E2E RPC Proxy tests
              run: |
                yarn test:e2e