name: PR Checks

on:
  pull_request:
    branches:
      - 'main'

jobs:
    build-lint:
      uses: ./.github/workflows/build-lint.yml
      secrets: inherit

    e2e-test:
      uses: ./.github/workflows/e2e-test.yml
      secrets: inherit

    trivy-scan:
      uses: ./.github/workflows/trivy-scan.yml
      secrets: inherit

            
    