name: Run Trivy Scan

on:
   workflow_call:

env:
  DOCKERFILE_LOCATION: "docker/rpc-proxy/Dockerfile"
  DOCKER_IMAGE_NAME: "vechain/sdk-rpc-proxy"

permissions:
  contents: read
  packages: write
  checks: write
  actions: read


jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_LOCATION }}
          load: true
          tags: "${{ env.DOCKER_IMAGE_NAME }}:for-trivy-scan"
          labels: |
            maintainer=vechain
            description="RPC Proxy for vechain Thor"
            build_timestamp=${{ github.event.after }}
            source=https://github.com/vechain/sdk-rpc-proxy
            commit_hash=${{ github.sha }}

      - name: Create .trivyignore file
        # "cross-spawn" is resolved as version 7.0.5 but Trivy keeps showing the error
        run: |
          echo "CVE-2024-21538" > .trivyignore
          echo "CVE-2024-13176" >> .trivyignore

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{env.DOCKER_IMAGE_NAME}}
          format: 'table'
          ignore-unfixed: true
          exit-code: '1'
          vuln-type: os,library
          severity: CRITICAL,HIGH,MEDIUM
          scanners: misconfig,vuln,secret
          trivyignores: .trivyignore
        env:
          # See https://github.com/aquasecurity/trivy/discussions/7538
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
