name: Unit Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node: [18, lts/*, latest]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  
            - name: Install & Patch packages
              run: yarn install
            
            - name: Build
              run: yarn build

            - name: Run unit tests
              run: |
                yarn test:unit